apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: php-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: my-php-app
        image: eperezacr.azurecr.io/eperez:1
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: secret-acr  
        # resources:
        #   limits:
        #       memory: "200Mi"
        #       cpu: "2"
        #   requests:
        #       memory: "100Mi"
        #       cpu: "0.5"