- name: Configure MySQL server for remote access
  hosts: vmdb
  become: true
  tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Instalar pymysql
      pip:
        name: pymysql
        state: present

    - name: Instalar MySQL
      apt:
        name: mysql-server
        state: present

    - name: Configurar MySQL bind-address y mysqlx-bind-address
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        state: present
      notify: restart mysql

    - name: Configurar MySQLX bind-address
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^mysqlx-bind-address'
        line: 'mysqlx-bind-address = 0.0.0.0'
        state: present
      notify: restart mysql

    - name: Crear base de datos
      mysql_db:
        name: concierto
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Crear usuario y contraseña con acceso remoto
      mysql_user:
        name: adminuser
        password: 1234
        priv: '*.*:ALL PRIVILEGES'
        host: '%'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Aplicar privilegios
      mysql_user:
        name: adminuser
        host: '%'
        priv: '*.*:ALL PRIVILEGES'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
    
    - name: Crear tabla tipo_entradas
      ansible.builtin.mysql_query:
        login_user: adminuser
        login_password: "1234"
        query: |
          CREATE TABLE IF NOT EXISTS concierto.tipo_entradas (
            id VARCHAR(36) PRIMARY KEY,
            tipo VARCHAR(30) NOT NULL,
            precio DECIMAL(10,2) NOT NULL
          );

    - name: Crear tabla entradas
      ansible.builtin.mysql_query:
        login_user: adminuser
        login_password: "1234"
        query: |
          CREATE TABLE IF NOT EXISTS concierto.entradas (
            id VARCHAR(36) PRIMARY KEY,
            fecha DATE NOT NULL,
            nombre VARCHAR(15) NOT NULL,
            apellidos VARCHAR(30) NOT NULL,
            telefono VARCHAR(9) NOT NULL,
            tipo_entrada VARCHAR(36),
            cantidad INT NOT NULL,
            precio DECIMAL(10,2) NOT NULL,
            FOREIGN KEY (tipo_entrada) REFERENCES tipo_entradas(id)
          );    
    - name: Rellenar tipo entradas
      ansible.builtin.mysql_query:
        login_user: adminuser
        login_password: "1234"
        query: |
          INSERT INTO tipo_entradas (id, tipo, precio) VALUES
          (UUID(), 'Menor', 10),
          (UUID(), 'Adulto', 5),
          (UUID(), 'Jubilado', 7);
          
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
        
