name: Ansible playbook

on:  workflow_dispatch

jobs:
  ansible:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: SSH key & host
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.PUBLIC_SSH_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa 
        ssh-keyscan -H 10.0.1.4 >> ~/.ssh/known_hosts      
  
    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install sshpass
        sudo apt-get install -y python3-pip
        sudo apt-get install -y ansible
    - name: Playbook
      run:  ansible-playbook -i ansible/inventory.ini ansible/playbook.yaml    
