name: self host runnerr

on:
  #workflow_dispatch:
  push:
    branches: #[main]
      - '*'
jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: eperezacr.azurecr.io
        username: eperezacr
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Connect to mv with bastion
      run: |
        az extension add --name ssh
        az network bastion ssh --name "eperezbastion" --resource-group "rg-eperez-dvfinlab" --target-resource-id "/subscriptions/86f76907-b9d5-46fa-a39d-aff8432a1868/resourceGroups/rg-eperez-dvfinlab/providers/Microsoft.Compute/virtualMachines/eperezvmdb" --auth-type "password" --username "eperez"
        sudo apt-get update
      
  
    - name: Install Ansible
      run: |
        sudo apt-get install sshpass
        sudo apt-get install -y ansible
    - name: Playbook
      run:  ansible-playbook -i ansible/inventory.ini ansible/install-mysql.yaml    
