name: self host runnner

on:
  #workflow_dispatch:
  push:
    branches: #[main]
      - '*'
jobs:
  ansible:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: SSH key & host
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa 
        ssh-keyscan -H 20.160.14.13 >> ~/.ssh/known_hosts      

    - name: Create tables
      run: |
        ssh eperez@20.160.14.13 '
        sudo mysql -u root
        USE concierto;
        CREATE TABLE IF NOT EXISTS tipo_entradas (
            id VARCHAR(36) NOT NULL,
            tipo VARCHAR(30),
            precio DECIMAL(10, 2),
            PRIMARY KEY (id)
        ); '  
  
    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install sshpass
        sudo apt-get install -y python3-pip
        sudo apt-get install -y ansible
    - name: Playbook
      run:  ansible-playbook -i ansible/inventory.ini ansible/install-mysql.yaml    
