name: Ansible playbook mysql

on:
  #workflow_dispatch:
  push:
    branches:
      - main
jobs:
  ansible:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install sshpass
        sudo apt-get install -y ansible

    - name: Playbook
      run:  ansible-playbook -i ansible/inventory.ini ansible/install-mysql.yaml
