name: Push image to Azure Container Registry

on:
  push:
    branches:
      - '*'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: eperezacr.azurecr.io
          username: eperezacr
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Docker image build, tag & push
        run: |
          docker build -t my-php-app ./app
          docker tag my-php-app eperezacr.azurecr.io/eperez:1
          docker push eperezacr.azurecr.io/eperez:1
