name: self host runner

on:
  #workflow_dispatch:
  push:
    branches:
      - '*'
jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: ssh
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa    

    - name: Conect to MV
      run: |
        ssh -o StrictHostKeyChecking=no eperez@40.68.215.165
        
