name: self host runner

on:
  #workflow_dispatch:
  push:
    branches:
      - '*'
jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH key & host
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H 13.95.171.10 >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/id_rsa  

    - name: Conect to MV
      run: |
        

        ssh eperez@13.95.171.1

        
